"""Initial schema

Revision ID: da9c7cbcff2a
Revises: 
Create Date: 2026-04-06 10:48:14.773792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9c7cbcff2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('track', sa.String(), nullable=False),
    sa.Column('car', sa.String(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_laps', sa.Integer(), nullable=False),
    sa.Column('best_lap_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_time_ms', sa.Integer(), nullable=False),
    sa.Column('sector_1_ms', sa.Integer(), nullable=False),
    sa.Column('sector_2_ms', sa.Integer(), nullable=False),
    sa.Column('sector_3_ms', sa.Integer(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('fuel_used', sa.Float(), nullable=False),
    sa.Column('fuel_remaining', sa.Float(), nullable=False),
    sa.Column('avg_tyre_temp_fl', sa.Float(), nullable=False),
    sa.Column('avg_tyre_temp_fr', sa.Float(), nullable=False),
    sa.Column('avg_tyre_temp_rl', sa.Float(), nullable=False),
    sa.Column('avg_tyre_temp_rr', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setup_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('tc_level', sa.Integer(), nullable=False),
    sa.Column('tc_cut', sa.Integer(), nullable=False),
    sa.Column('abs_level', sa.Integer(), nullable=False),
    sa.Column('engine_map', sa.Integer(), nullable=False),
    sa.Column('brake_bias', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setup_snapshots')
    op.drop_table('laps')
    op.drop_table('sessions')
    # ### end Alembic commands ###
